### ISSUE TITLE
Feedback - Proyecto cipher

### ISSUE THREAD

**Issue by shirley-startary** [JudithCortes/cdmx-2018-06-bc-core-am-cipher#1]
Hola @JudithCortes 
Estuve revisando tu proyecto, y tengo algunos comentarios:

- Utilizar HTML semantico, por ejemplo utilizar etiquetas como:  `<header></header> , <nav></nav>, <section></section>, <articule></articule>, <footer></footer>, <aside></aside>`.

- Bien por haber trabajado en le README, aunque también debe de incluir los requerimientos, instalación y ser mas detallado de como se utiliza, así como documentar el proceso de UX.

- El validador html https://validator.w3.org/ marca errores y warnings. Utiliza esta herramienta antes de tus entregas para detectar que puedes mejorar en tu código html!

- Importante que empieces a abstraer y reusar código en todos los archivos; por ejemplo en el archivo de css tienes la propiedad en `text-align: center;` en muchos elementos diferentes, pudiendo poner dicha propiedad en una clase, y aplicar esa clase en los elementos que lo requieran.

- Debes de utilizar  nombres de identificadores (variables, funciones, archivos, carpetas, ...) descriptivos.
 
- En las lineas 15, 18, 24, 27, 37 del archivo `index.html` tienes etiquetas que no han sido bien cerradas o han sido abiertas y nunca cerradas.

- Importante que cuando agregues un atributo _id_ debe ser único, ten cuidado, ya que en las lineas 11, 13 del `index.html` tienes 2 elementos con el mismo _id_.

-En tu archivo index.html tiene errores en las lineas 42, 44 ; estas agregando atributos a las etiquetas en donde el valor debe ir encerrado entre comillas dobles " Ej. `src=cipher.js` lo correcto debe ser `src="cipher.js"`.

Muchas felicidades por tu alcance en este primer proyecto, mucho éxito en los que viene; te invito que sigas trabajando en el proyecto y completar lo que aun falte y corregir los errores 👍.

**Comment by JudithCortes** [comment]
Hola Silvana!! Gracias por el feedback!!! No puedo creer que hasta hoy me di cuenta del issue :0 jaja, te lo agradezco muchísimo de verdad, no había visto estos errores, me ocuparé en mejorarlos. Saludos.
